### ISSUE TITLE
Replace BackpressureBufferLastOperator with onBackpressureLatest in RxJava 1.1

### ISSUE THREAD

**Issue by kotucz** [nvanbenschoten/RxSensor#2]
BackpressureBufferLastOperator class copied from SqlBrite can be replaced with the native onBackpressureLatest() operator, whic is available in RxJava 1.1.

See related issue in SqlBrite
https://github.com/square/sqlbrite/issues/73

**Comment by nvb** [comment]
Hi Tomáš, thanks for bringing this up! Switching from the custom `BackpressureBufferLastOperator` to the `onBackpressureLatest()` operator seems like the right approach.

Do you want to take a stab at making the change, or would you like me to go ahead and switch this over?

**Comment by kotucz** [comment]
Thanks. I could try it, but I'll be able to do it end of this week
